### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RUKYIZE-12**

### CODE REVIEW

**Comment by RUKYIZE-12** [comment]
i added my content.js file and also cart.js file as my contribution to the project.

**Comment by RUKYIZE-12** [comment]
i added the cart.js and content.js file as my contribution to this project.

**Comment by EngrBilalAbdullahi** [comment]
Good Rukaya.

**Review by EngrBilalAbdullahi — COMMENTED** [review]
that's good

**Pull request merged**
